included:
 - Sources
 - Tests
excluded:
 - Carthage
 - Pods
opt_in_rules:
 - missing_docs
force_cast: warning
force_try:
 severity: warning
type_name:
 min_length: 2
 max_length:
  warning: 40
  error: 50
variable_name:
 min_length:
  error: 2
